Now back to automatically loading the defaults for remote configuration
For local configuration, will still fail to load, but will provide all of the fields failing validation, not just the first.

Arguably we could have a CLI arg that loads default config for local resources also, but Im not sure that it should be the default, as we'd be hiding actual configuration issues and never be made aware.

Error will be
```
java.lang.IllegalArgumentException: The specified network configuration had missing or invalid values for constants GOSSIP_MAX_SIZE, ATTESTATION_SUBNET_PREFIX_BITS, RESP_TIMEOUT, ATTESTATION_SUBNET_EXTRA_BITS, MAXIMUM_GOSSIP_CLOCK_DISPARITY, MAX_CHUNK_SIZE, ATTESTATION_PROPAGATION_SLOT_RANGE, MESSAGE_DOMAIN_INVALID_SNAPPY, TTFB_TIMEOUT, EPOCHS_PER_SUBNET_SUBSCRIPTION, MESSAGE_DOMAIN_VALID_SNAPPY, ATTESTATION_SUBNET_COUNT, MIN_EPOCHS_FOR_BLOCK_REQUESTS, MAX_REQUEST_BLOCKS
```
which is arguably harder to read, but doesnt force you to fix one, rinse repeat until you've got a valid configuration.

Signed-off-by: Paul Harris <paul.harris@consensys.net>